const colorList = [
    // --- DIŞ CEPHE RENKLERİ ---
    { name: 'ANTRASİT', hex: '#374151', type: 'dis' },
    { name: 'KAYRA', hex: '#d1d5db', type: 'dis' },
    { name: 'KAPADOKYA', hex: '#a8a29e', type: 'dis' },
    { name: 'HİSAR', hex: '#78716c', type: 'dis' },
    { name: 'TRUVA', hex: '#9ca3af', type: 'dis' },
    { name: 'EFES', hex: '#e5e7eb', type: 'dis' },
    { name: 'ASSOS', hex: '#d1d5db', type: 'dis' },
    { name: 'BERGAMA', hex: '#f3f4f6', type: 'dis' },
    { name: 'KİREMİT', hex: '#b91c1c', type: 'dis' },
    { name: 'TAŞ GRİSİ', hex: '#6b7280', type: 'dis' },
    { name: 'KREM', hex: '#fef3c7', type: 'dis' },
    { name: 'BEJ', hex: '#f5f5dc', type: 'dis' },
    { name: 'KUM FIRTINASI', hex: '#d2b48c', type: 'dis' },
    // --- EK DIŞ CEPHE RENKLERİ ---
{ name: 'AIDA 10', hex: '#f5f1ea', type: 'dis' },
{ name: 'AIDA 20', hex: '#e7dccd', type: 'dis' },
{ name: 'AIDA 30', hex: '#d6c4ad', type: 'dis' },

{ name: 'ALMOND 10', hex: '#fdf6ec', type: 'dis' },
{ name: 'ALMOND 20', hex: '#ead7bd', type: 'dis' },
{ name: 'ALMOND 30', hex: '#d2b08c', type: 'dis' },

{ name: 'ASTORIA 10', hex: '#f3f4f6', type: 'dis' },
{ name: 'ASTORIA 20', hex: '#d1d5db', type: 'dis' },
{ name: 'ASTORIA 30', hex: '#9ca3af', type: 'dis' },

{ name: 'AURA 10', hex: '#faf5ff', type: 'dis' },
{ name: 'AURA 20', hex: '#e9d5ff', type: 'dis' },
{ name: 'AURA 30', hex: '#c084fc', type: 'dis' },

{ name: 'AZUR 10', hex: '#eff6ff', type: 'dis' },
{ name: 'AZUR 20', hex: '#93c5fd', type: 'dis' },
{ name: 'AZUR 30', hex: '#2563eb', type: 'dis' },

{ name: 'BAMBOO 10', hex: '#f7fee7', type: 'dis' },
{ name: 'BAMBOO 20', hex: '#bef264', type: 'dis' },
{ name: 'BAMBOO 30', hex: '#65a30d', type: 'dis' },

{ name: 'BEGONIA 10', hex: '#fff1f2', type: 'dis' },
{ name: 'BEGONIA 20', hex: '#fda4af', type: 'dis' },
{ name: 'BEGONIA 30', hex: '#e11d48', type: 'dis' },

{ name: 'BELLA 10', hex: '#fdf2f8', type: 'dis' },
{ name: 'BELLA 20', hex: '#f9a8d4', type: 'dis' },
{ name: 'BELLA 30', hex: '#db2777', type: 'dis' },

{ name: 'BERMUDA 10', hex: '#ecfeff', type: 'dis' },
{ name: 'BERMUDA 20', hex: '#67e8f9', type: 'dis' },
{ name: 'BERMUDA 30', hex: '#0891b2', type: 'dis' },

{ name: 'BISTRO 10', hex: '#fafaf9', type: 'dis' },
{ name: 'BISTRO 20', hex: '#d6d3d1', type: 'dis' },
{ name: 'BISTRO 30', hex: '#78716c', type: 'dis' },

{ name: 'BRONZE 10', hex: '#fef3c7', type: 'dis' },
{ name: 'BRONZE 20', hex: '#d97706', type: 'dis' },
{ name: 'BRONZE 30', hex: '#92400e', type: 'dis' },

{ name: 'CACAO 10', hex: '#f5ebe0', type: 'dis' },
{ name: 'CACAO 20', hex: '#b08968', type: 'dis' },
{ name: 'CACAO 30', hex: '#7f5539', type: 'dis' },

{ name: 'CAMEL 10', hex: '#fff7ed', type: 'dis' },
{ name: 'CAMEL 20', hex: '#fdba74', type: 'dis' },
{ name: 'CAMEL 30', hex: '#c2410c', type: 'dis' },

{ name: 'CANYON 10', hex: '#fef2f2', type: 'dis' },
{ name: 'CANYON 20', hex: '#fca5a5', type: 'dis' },
{ name: 'CANYON 30', hex: '#b91c1c', type: 'dis' },

{ name: 'CAPRI 10', hex: '#eff6ff', type: 'dis' },
{ name: 'CAPRI 20', hex: '#60a5fa', type: 'dis' },
{ name: 'CAPRI 30', hex: '#1d4ed8', type: 'dis' },

{ name: 'COSMOS 10', hex: '#faf5ff', type: 'dis' },
{ name: 'COSMOS 20', hex: '#d8b4fe', type: 'dis' },
{ name: 'COSMOS 30', hex: '#9333ea', type: 'dis' },

{ name: 'DARK 10', hex: '#d1d5db', type: 'dis' },
{ name: 'DARK 20', hex: '#4b5563', type: 'dis' },
{ name: 'DARK 30', hex: '#111827', type: 'dis' },

{ name: 'DIVA 10', hex: '#fdf2f8', type: 'dis' },
{ name: 'DIVA 20', hex: '#f472b6', type: 'dis' },
{ name: 'DIVA 30', hex: '#be185d', type: 'dis' },

{ name: 'EDEN 10', hex: '#f0fdf4', type: 'dis' },
{ name: 'EDEN 20', hex: '#4ade80', type: 'dis' },
{ name: 'EDEN 30', hex: '#166534', type: 'dis' },

{ name: 'FERRE 10', hex: '#f5f5f4', type: 'dis' },
{ name: 'FERRE 20', hex: '#a8a29e', type: 'dis' },
{ name: 'FERRE 30', hex: '#44403c', type: 'dis' },

{ name: 'FLAMINGO 10', hex: '#fff1f2', type: 'dis' },
{ name: 'FLAMINGO 20', hex: '#fb7185', type: 'dis' },
{ name: 'FLAMINGO 30', hex: '#be123c', type: 'dis' },

{ name: 'GARDEN 10', hex: '#f0fdf4', type: 'dis' },
{ name: 'GARDEN 20', hex: '#86efac', type: 'dis' },
{ name: 'GARDEN 30', hex: '#15803d', type: 'dis' },

{ name: 'GOLD 10', hex: '#fefce8', type: 'dis' },
{ name: 'GOLD 20', hex: '#facc15', type: 'dis' },
{ name: 'GOLD 30', hex: '#a16207', type: 'dis' },

{ name: 'GREY 10', hex: '#f3f4f6', type: 'dis' },
{ name: 'GREY 20', hex: '#9ca3af', type: 'dis' },
{ name: 'GREY 30', hex: '#374151', type: 'dis' },

{ name: 'HARMONY 10', hex: '#f8fafc', type: 'dis' },
{ name: 'HARMONY 20', hex: '#cbd5e1', type: 'dis' },
{ name: 'HARMONY 30', hex: '#475569', type: 'dis' },

{ name: 'HAZEL 10', hex: '#fefce8', type: 'dis' },
{ name: 'HAZEL 20', hex: '#d6d3d1', type: 'dis' },
{ name: 'HAZEL 30', hex: '#78716c', type: 'dis' },

{ name: 'HENNA 10', hex: '#fff7ed', type: 'dis' },
{ name: 'HENNA 20', hex: '#fb923c', type: 'dis' },
{ name: 'HENNA 30', hex: '#9a3412', type: 'dis' },

{ name: 'HERBAL 10', hex: '#f7fee7', type: 'dis' },
{ name: 'HERBAL 20', hex: '#a3e635', type: 'dis' },
{ name: 'HERBAL 30', hex: '#4d7c0f', type: 'dis' },

{ name: 'INCA 10', hex: '#fef3c7', type: 'dis' },
{ name: 'INCA 20', hex: '#f59e0b', type: 'dis' },
{ name: 'INCA 30', hex: '#92400e', type: 'dis' },

{ name: 'INDIGO 10', hex: '#eef2ff', type: 'dis' },
{ name: 'INDIGO 20', hex: '#818cf8', type: 'dis' },
{ name: 'INDIGO 30', hex: '#4338ca', type: 'dis' },

{ name: 'KIWI 10', hex: '#f7fee7', type: 'dis' },
{ name: 'KIWI 20', hex: '#84cc16', type: 'dis' },
{ name: 'KIWI 30', hex: '#365314', type: 'dis' },

{ name: 'KVKK 10', hex: '#e5e7eb', type: 'dis' },

{ name: 'LAGUNA 10', hex: '#ecfeff', type: 'dis' },
{ name: 'LAGUNA 20', hex: '#67e8f9', type: 'dis' },
{ name: 'LAGUNA 30', hex: '#155e75', type: 'dis' },

{ name: 'LAKE 10', hex: '#eff6ff', type: 'dis' },
{ name: 'LAKE 20', hex: '#7dd3fc', type: 'dis' },
{ name: 'LAKE 30', hex: '#0369a1', type: 'dis' },

{ name: 'LEMON 10', hex: '#fefce8', type: 'dis' },
{ name: 'LEMON 20', hex: '#fde047', type: 'dis' },
{ name: 'LEMON 30', hex: '#ca8a04', type: 'dis' },

{ name: 'LINEN 10', hex: '#faf7f2', type: 'dis' },
{ name: 'LINEN 20', hex: '#d6ccc2', type: 'dis' },
{ name: 'LINEN 30', hex: '#a68a64', type: 'dis' },

{ name: 'LOTUS 10', hex: '#fdf2f8', type: 'dis' },
{ name: 'LOTUS 20', hex: '#f9a8d4', type: 'dis' },
{ name: 'LOTUS 30', hex: '#9d174d', type: 'dis' },

{ name: 'MANGO 10', hex: '#fff7ed', type: 'dis' },
{ name: 'MANGO 20', hex: '#fb923c', type: 'dis' },
{ name: 'MANGO 30', hex: '#c2410c', type: 'dis' },

{ name: 'MARINA 10', hex: '#eff6ff', type: 'dis' },
{ name: 'MARINA 20', hex: '#38bdf8', type: 'dis' },
{ name: 'MARINA 30', hex: '#075985', type: 'dis' },

{ name: 'MELON 10', hex: '#fff7ed', type: 'dis' },
{ name: 'MELON 20', hex: '#fdba74', type: 'dis' },
{ name: 'MELON 30', hex: '#ea580c', type: 'dis' },

{ name: 'MELROSE 10', hex: '#faf5ff', type: 'dis' },
{ name: 'MELROSE 20', hex: '#d8b4fe', type: 'dis' },
{ name: 'MELROSE 30', hex: '#7e22ce', type: 'dis' },

{ name: 'MELROT 10', hex: '#fef2f2', type: 'dis' },
{ name: 'MERLOT 20', hex: '#991b1b', type: 'dis' },
{ name: 'MERLOT 30', hex: '#450a0a', type: 'dis' },

{ name: 'MIMOSA 10', hex: '#fefce8', type: 'dis' },
{ name: 'MIMOSA 20', hex: '#fde047', type: 'dis' },
{ name: 'MIMOSA 30', hex: '#a16207', type: 'dis' },

{ name: 'MINERAL 10', hex: '#f8fafc', type: 'dis' },
{ name: 'MINERAL 20', hex: '#94a3b8', type: 'dis' },
{ name: 'MINERAL 30', hex: '#334155', type: 'dis' },

{ name: 'MOCHA 10', hex: '#faf7f2', type: 'dis' },
{ name: 'MOCHA 20', hex: '#a68a64', type: 'dis' },
{ name: 'MOCHA 30', hex: '#6f4e37', type: 'dis' },

{ name: 'MONTANA 10', hex: '#f1f5f9', type: 'dis' },
{ name: 'MONTANA 20', hex: '#64748b', type: 'dis' },
{ name: 'MONTANA 30', hex: '#1e293b', type: 'dis' },

{ name: 'NATURAL 10', hex: '#fafaf9', type: 'dis' },
{ name: 'NATURAL 20', hex: '#d6d3d1', type: 'dis' },
{ name: 'NATURAL 30', hex: '#78716c', type: 'dis' },

{ name: 'NIAGARA 10', hex: '#ecfeff', type: 'dis' },
{ name: 'NIAGARA 20', hex: '#22d3ee', type: 'dis' },
{ name: 'NIAGARA 30', hex: '#164e63', type: 'dis' },

{ name: 'OLIVE 10', hex: '#f7fee7', type: 'dis' },
{ name: 'OLIVE 20', hex: '#84cc16', type: 'dis' },
{ name: 'OLIVE 30', hex: '#3f6212', type: 'dis' },

{ name: 'OPAL 10', hex: '#f8fafc', type: 'dis' },
{ name: 'OPAL 20', hex: '#cbd5e1', type: 'dis' },
{ name: 'OPAL 30', hex: '#475569', type: 'dis' },

{ name: 'OPERA 10', hex: '#faf5ff', type: 'dis' },
{ name: 'OPERA 20', hex: '#c084fc', type: 'dis' },
{ name: 'OPERA 30', hex: '#6b21a8', type: 'dis' },

{ name: 'ORANGE 10', hex: '#fff7ed', type: 'dis' },
{ name: 'ORANGE 20', hex: '#fb923c', type: 'dis' },
{ name: 'ORANGE 30', hex: '#c2410c', type: 'dis' },

{ name: 'ORGANIC 10', hex: '#f0fdf4', type: 'dis' },
{ name: 'ORGANIC 20', hex: '#86efac', type: 'dis' },
{ name: 'ORGANIC 30', hex: '#166534', type: 'dis' },

    // --- İÇ CEPHE RENKLERİ ---
    { name: 'CANVAS_55', hex: '#ede6d9', type: 'ic' }, { name: 'LILAC_130', hex: '#e6e6fa', type: 'ic' },
    { name: 'FOREST_130', hex: '#2d4c3b', type: 'ic' }, { name: 'FLORA_10', hex: '#f0fdf4', type: 'ic' },
    { name: 'DAISY_85', hex: '#fef9c3', type: 'ic' }, { name: 'MIST_25', hex: '#f1f5f9', type: 'ic' },
    { name: 'WIND_20', hex: '#f8fafc', type: 'ic' }, { name: 'APRIL_20', hex: '#e2f3e4', type: 'ic' },
    { name: 'SPA_5', hex: '#ecfeff', type: 'ic' }, { name: 'LILAC_195', hex: '#f3e8ff', type: 'ic' },
    { name: 'MARZIPAN_10', hex: '#fef3c7', type: 'ic' }, { name: 'LATTE_50', hex: '#ece0d1', type: 'ic' },
    { name: 'LATTE_200', hex: '#dbcaac', type: 'ic' }, { name: 'CANVAS_115', hex: '#e5ddd0', type: 'ic' },
    { name: 'CARNAVAL_15', hex: '#fce7f3', type: 'ic' }, { name: 'BONSAI_30', hex: '#ecfccb', type: 'ic' },
    { name: 'PINK_10', hex: '#fdf2f8', type: 'ic' }, { name: 'SATIN_5', hex: '#f8fafc', type: 'ic' },
    { name: 'SATIN_10', hex: '#f1f5f9', type: 'ic' }, { name: 'JASMINE_5', hex: '#fff7ed', type: 'ic' },
    { name: 'BONSAI_75', hex: '#d9f99d', type: 'ic' }, { name: 'CANVAS_165', hex: '#d6ccc2', type: 'ic' },
    { name: 'MARZIPAN_80', hex: '#fde68a', type: 'ic' }, { name: 'DENIM_45', hex: '#dbeafe', type: 'ic' },
    { name: 'NECTAR_110', hex: '#fbbf24', type: 'ic' }, { name: 'NECTAR_30', hex: '#fef3c7', type: 'ic' },
    { name: 'ZENCEFİL', hex: '#d97706', type: 'ic' }, { name: 'CANVAS_175', hex: '#ccc3b8', type: 'ic' },
    { name: 'BONSAI_20', hex: '#f7fee7', type: 'ic' }, { name: 'CARMEN_55', hex: '#ef4444', type: 'ic' },
    { name: 'LILAC_155', hex: '#faf5ff', type: 'ic' }, { name: 'CANVAS_125', hex: '#e2d9cc', type: 'ic' },
    { name: 'DENIM_180', hex: '#1e3a8a', type: 'ic' }, { name: 'BONSAI_95', hex: '#bef264', type: 'ic' },
    { name: 'BANANA_15', hex: '#fef9c3', type: 'ic' }, { name: 'BONSAI_100', hex: '#a3e635', type: 'ic' },
    { name: 'FOREST_75', hex: '#4d7c0f', type: 'ic' }, { name: 'LATTE_75', hex: '#dfd3c3', type: 'ic' },
    { name: 'CANVAS_135', hex: '#ded4c7', type: 'ic' }, { name: 'CARMEN_15', hex: '#fee2e2', type: 'ic' },
    { name: 'LATTE_100', hex: '#d7c9b7', type: 'ic' }, { name: 'LATTE_205', hex: '#d4c3ad', type: 'ic' },
    { name: 'DENIM_35', hex: '#eff6ff', type: 'ic' }, { name: 'LATTE_65', hex: '#e4d8c8', type: 'ic' },
    { name: 'BONSAI_215', hex: '#3f6212', type: 'ic' }, { name: 'FOREST_10', hex: '#f0fdf4', type: 'ic' },
    { name: 'FOREST_30', hex: '#dcfce7', type: 'ic' }, { name: 'DENIM_175', hex: '#1e40af', type: 'ic' },
    { name: 'LILAC_105', hex: '#f5f3ff', type: 'ic' }, { name: 'AQUA_10', hex: '#e0f2fe', type: 'ic' },
    { name: 'CANVAS_35', hex: '#f5f1ea', type: 'ic' }, { name: 'CANVAS_85', hex: '#eee4d5', type: 'ic' },
    { name: 'DAISY_60', hex: '#fef08a', type: 'ic' }, { name: 'CANVAS_65', hex: '#f2eae0', type: 'ic' },
    { name: 'BONSAI_145', hex: '#65a30d', type: 'ic' }, { name: 'DAISY_75', hex: '#fde047', type: 'ic' },
    { name: 'LILAC_135', hex: '#ede9fe', type: 'ic' }, { name: 'MIST_10', hex: '#f8fafc', type: 'ic' },
    { name: 'LILAC_25', hex: '#fdf4ff', type: 'ic' }, { name: 'NECTAR_195', hex: '#78350f', type: 'ic' },
    { name: 'CANVAS_5', hex: '#fafaf9', type: 'ic' }, { name: 'CREAM_5', hex: '#fffbeb', type: 'ic' },
    { name: 'POWDER_20', hex: '#fce7f3', type: 'ic' }, { name: 'MIST_125', hex: '#cbd5e1', type: 'ic' },
    { name: 'LATTE_35', hex: '#f3ece3', type: 'ic' }, { name: 'BADEM', hex: '#ffedd5', type: 'ic' },
    { name: 'DAISY_140', hex: '#ca8a04', type: 'ic' }, { name: 'MIST_40', hex: '#f1f5f9', type: 'ic' },
    { name: 'ŞEKER PEMBE', hex: '#f472b6', type: 'ic' }, { name: 'DENIM_70', hex: '#bfdbfe', type: 'ic' },
    { name: 'CARMEN_25', hex: '#fecaca', type: 'ic' }, { name: 'CANVAS_75', hex: '#f0e7db', type: 'ic' },
    { name: 'FOREST_160', hex: '#166534', type: 'ic' }, { name: 'SPA_15', hex: '#cffafe', type: 'ic' },
    { name: 'COTTON_20', hex: '#f9fafb', type: 'ic' }, { name: 'PUDRA', hex: '#fbcfe8', type: 'ic' },
    { name: 'FOREST_100', hex: '#22c55e', type: 'ic' }, { name: 'CANVAS_140', hex: '#dbd1c2', type: 'ic' },
    { name: 'LILAC_90', hex: '#fae8ff', type: 'ic' }, { name: 'LATTE_105', hex: '#d4c5b3', type: 'ic' },
    { name: 'LATTE_220', hex: '#ccbcab', type: 'ic' }, { name: 'FOREST_170', hex: '#14532d', type: 'ic' },
    { name: 'BONSAI_180', hex: '#4d7c0f', type: 'ic' }, { name: 'MIST_120', hex: '#d1d5db', type: 'ic' },
    { name: 'NECTAR_185', hex: '#92400e', type: 'ic' }, { name: 'CARMEN_70', hex: '#dc2626', type: 'ic' },
    { name: 'CARMEN_120', hex: '#991b1b', type: 'ic' }, { name: 'NECTAR_105', hex: '#d97706', type: 'ic' },
    { name: 'STONE_20', hex: '#e5e7eb', type: 'ic' }, { name: 'CANVAS_90', hex: '#ebe1d1', type: 'ic' },
    { name: 'SALSA_20', hex: '#fca5a5', type: 'ic' }, { name: 'BONSAI_245', hex: '#1a2e05', type: 'ic' },
    { name: 'CANVAS_15', hex: '#fcfaf7', type: 'ic' }, { name: 'PARADISE_15', hex: '#ecfeff', type: 'ic' },
    { name: 'LATTE_175', hex: '#beaf9d', type: 'ic' }, { name: 'MIST_95', hex: '#e2e8f0', type: 'ic' },
    { name: 'CLAY_5', hex: '#fafaf9', type: 'ic' }, { name: 'NECTAR_120', hex: '#b45309', type: 'ic' },
    { name: 'CARMEN_80', hex: '#b91c1c', type: 'ic' }, { name: 'DENIM_155', hex: '#2563eb', type: 'ic' },
    { name: 'LILAC_5', hex: '#faf5ff', type: 'ic' }, { name: 'BONSAI_235', hex: '#365314', type: 'ic' },
    { name: 'SALSA_10', hex: '#fee2e2', type: 'ic' }, { name: 'DENIM_200', hex: '#172554', type: 'ic' },
    { name: 'MARZIPAN_50', hex: '#fef08a', type: 'ic' }, { name: 'NECTAR_15', hex: '#fffbeb', type: 'ic' },
    { name: 'DAISY_40', hex: '#fef9c3', type: 'ic' }, { name: 'DENIM_50', hex: '#dbeafe', type: 'ic' },
    { name: 'BANANA_5', hex: '#fffdf0', type: 'ic' }, { name: 'BONSAI_40', hex: '#f7fee7', type: 'ic' },
    { name: 'CANVAS_50', hex: '#f0ede6', type: 'ic' }, { name: 'DENIM_65', hex: '#bfdbfe', type: 'ic' },
    { name: 'FOREST_45', hex: '#bbf7d0', type: 'ic' }, { name: 'STONE_15', hex: '#f3f4f6', type: 'ic' },
    { name: 'BONSAI_115', hex: '#84cc16', type: 'ic' }, { name: 'FOREST_95', hex: '#4ade80', type: 'ic' },
    { name: 'LILAC_35', hex: '#f5f3ff', type: 'ic' }, { name: 'VADİ', hex: '#14532d', type: 'ic' },
    { name: 'ZEN_10', hex: '#f9fafb', type: 'ic' }, { name: 'LATTE_215', hex: '#c8b8a5', type: 'ic' },
    { name: 'DENIM_170', hex: '#1d4ed8', type: 'ic' }, { name: 'CARMEN_10', hex: '#fef2f2', type: 'ic' },
    { name: 'LATTE_145', hex: '#ccbead', type: 'ic' }, { name: 'BONSAI_170', hex: '#3f6212', type: 'ic' },
    { name: 'DENIM_190', hex: '#1e3a8a', type: 'ic' }, { name: 'NECTAR_160', hex: '#a16207', type: 'ic' },
    { name: 'FOREST_115', hex: '#15803d', type: 'ic' }, { name: 'CANVAS_185', hex: '#c5baa9', type: 'ic' },
    { name: 'CANVAS_20', hex: '#faf8f5', type: 'ic' }, { name: 'CARMEN_30', hex: '#fca5a5', type: 'ic' },
    { name: 'FOREST_180', hex: '#064e3b', type: 'ic' }, { name: 'DENIM_75', hex: '#93c5fd', type: 'ic' },
    { name: 'CARMEN_20', hex: '#fee2e2', type: 'ic' }, { name: 'LATTE_90', hex: '#dad0c0', type: 'ic' },
    { name: 'AQUA_15', hex: '#bae6fd', type: 'ic' }, { name: 'CARMEN_5', hex: '#fff1f1', type: 'ic' },
    { name: 'LATTE_225', hex: '#c3b3a1', type: 'ic' }, { name: 'DAISY_35', hex: '#fefce8', type: 'ic' },
    { name: 'DENIM_95', hex: '#60a5fa', type: 'ic' }, { name: 'JASMINE_15', hex: '#fff7ed', type: 'ic' },
    { name: 'LILAC_125', hex: '#ddd6fe', type: 'ic' }, { name: 'FLORA_5', hex: '#f0fdf4', type: 'ic' },
    { name: 'DENIM_110', hex: '#3b82f6', type: 'ic' }, { name: 'LILAC_70', hex: '#f3e8ff', type: 'ic' },
    { name: 'MIST_90', hex: '#e2e8f0', type: 'ic' }, { name: 'BONSAI_185', hex: '#365314', type: 'ic' },
    { name: 'NECTAR_150', hex: '#b45309', type: 'ic' }, { name: 'MARZIPAN_20', hex: '#fefce8', type: 'ic' },
    { name: 'KADİFE ÇİÇEĞİ', hex: '#f97316', type: 'ic' }, { name: 'ÇAY YEŞİLİ', hex: '#86efac', type: 'ic' },
    { name: 'CARMEN_115', hex: '#991b1b', type: 'ic' }, { name: 'DAISY_125', hex: '#eab308', type: 'ic' },
    { name: 'DENIM_125', hex: '#2563eb', type: 'ic' }, { name: 'PINK_15', hex: '#fce7f3', type: 'ic' },
    { name: 'LATTE_195', hex: '#dac7ac', type: 'ic' }, { name: 'DAISY_80', hex: '#fde047', type: 'ic' },
    { name: 'ZEN_5', hex: '#f9fafb', type: 'ic' }, { name: 'FOREST_110', hex: '#16a34a', type: 'ic' },
    { name: 'FOREST_140', hex: '#166534', type: 'ic' }, { name: 'MARZIPAN_100', hex: '#eab308', type: 'ic' },
    { name: 'CANVAS_200', hex: '#bdb19f', type: 'ic' }, { name: 'MARZIPAN_55', hex: '#fde047', type: 'ic' },
    { name: 'CANVAS_130', hex: '#e0d6c7', type: 'ic' }, { name: 'KÜL GRİ', hex: '#94a3b8', type: 'ic' },
    { name: 'FOREST_175', hex: '#065f46', type: 'ic' }, { name: 'LILAC_190', hex: '#c084fc', type: 'ic' },
    { name: 'CARMEN_125', hex: '#7f1d1d', type: 'ic' }, { name: 'LATTE_70', hex: '#e2d6c3', type: 'ic' },
    { name: 'FOREST_150', hex: '#15803d', type: 'ic' }, { name: 'BONSAI_25', hex: '#f7fee7', type: 'ic' },
    { name: 'CANVAS_100', hex: '#e8decb', type: 'ic' }, { name: 'ROMANTIC_20', hex: '#fce7f3', type: 'ic' },
    { name: 'FOREST_145', hex: '#14532d', type: 'ic' }, { name: 'SALSA_5', hex: '#fff1f1', type: 'ic' },
    { name: 'WIND_15', hex: '#f8fafc', type: 'ic' }, { name: 'PINK_5', hex: '#fff1f2', type: 'ic' },
    { name: 'BONSAI_125', hex: '#4d7c0f', type: 'ic' }, { name: 'MARZIPAN_110', hex: '#ca8a04', type: 'ic' },
    { name: 'MIST_15', hex: '#f8fafc', type: 'ic' }, { name: 'CLAY_10', hex: '#f5f5f4', type: 'ic' },
    { name: 'DENIM_165', hex: '#1d4ed8', type: 'ic' }, { name: 'NECTAR_130', hex: '#92400e', type: 'ic' },
    { name: 'FOREST_120', hex: '#166534', type: 'ic' }, { name: 'LATTE_15', hex: '#fdfbf9', type: 'ic' },
    { name: 'DENIM_40', hex: '#eff6ff', type: 'ic' }, { name: 'LATTE_30', hex: '#f5efea', type: 'ic' },
    { name: 'LATTE_95', hex: '#d8cdbe', type: 'ic' }, { name: 'MARZIPAN_45', hex: '#fef08a', type: 'ic' },
    { name: 'LATTE_110', hex: '#d1c2af', type: 'ic' }, { name: 'MUM ÇİÇEĞİ', hex: '#fdf2f8', type: 'ic' },
    { name: 'BONSAI_240', hex: '#1a2e05', type: 'ic' }, { name: 'FOREST_80', hex: '#15803d', type: 'ic' },
    { name: 'STONE_5', hex: '#fafaf9', type: 'ic' }, { name: 'DENIM_85', hex: '#93c5fd', type: 'ic' },
    { name: 'APRIL_5', hex: '#f0fdf4', type: 'ic' }, { name: 'NECTAR_20', hex: '#fffbeb', type: 'ic' },
    { name: 'MARZIPAN_135', hex: '#a16207', type: 'ic' }, { name: 'JASMINE_20', hex: '#ffedd5', type: 'ic' },
    { name: 'DENIM_100', hex: '#3b82f6', type: 'ic' }, { name: 'IŞIL', hex: '#fff7ed', type: 'ic' },
    { name: 'DENIM_185', hex: '#1e3a8a', type: 'ic' }, { name: 'LATTE_20', hex: '#faf7f2', type: 'ic' },
    { name: 'MARZIPAN_140', hex: '#854d0e', type: 'ic' }, { name: 'LATTE_190', hex: '#dbcaac', type: 'ic' },
    { name: 'CANVAS_80', hex: '#f1e9dc', type: 'ic' }, { name: 'STONE_10', hex: '#f9fafb', type: 'ic' },
    { name: 'MARZIPAN_5', hex: '#fffbeb', type: 'ic' }, { name: 'MIST_45', hex: '#f1f5f9', type: 'ic' },
    { name: 'LATTE_155', hex: '#c9bca8', type: 'ic' }, { name: 'BONSAI_10', hex: '#f7fee7', type: 'ic' },
    { name: 'BONSAI_130', hex: '#4d7c0f', type: 'ic' }, { name: 'DENIM_5', hex: '#f0f9ff', type: 'ic' },
    { name: 'LATTE_45', hex: '#ede4d6', type: 'ic' }, { name: 'DENIM_195', hex: '#172554', type: 'ic' },
    { name: 'LATTE_120', hex: '#cec0ad', type: 'ic' }, { name: 'LILAC_45', hex: '#f3e8ff', type: 'ic' },
    { name: 'MARZIPAN_85', hex: '#facc15', type: 'ic' }, { name: 'LILAC_40', hex: '#faf5ff', type: 'ic' },
    { name: 'MARZIPAN_125', hex: '#ca8a04', type: 'ic' }, { name: 'BONSAI_200', hex: '#3f6212', type: 'ic' },
    { name: 'CARMEN_35', hex: '#f87171', type: 'ic' }, { name: 'DENIM_120', hex: '#2563eb', type: 'ic' },
    { name: 'LILAC_140', hex: '#ddd6fe', type: 'ic' }, { name: 'BONSAI_15', hex: '#f7fee7', type: 'ic' },
    { name: 'CANVAS_155', hex: '#d9cfbf', type: 'ic' }, { name: 'BANANA_20', hex: '#fef08a', type: 'ic' },
    { name: 'DAISY_25', hex: '#fefce8', type: 'ic' }, { name: 'NECTAR_25', hex: '#fef3c7', type: 'ic' },
    { name: 'LATTE_55', hex: '#e8ddd0', type: 'ic' }, { name: 'SOMON', hex: '#ffa07a', type: 'ic' },
    { name: 'DAISY_150', hex: '#a16207', type: 'ic' }, { name: 'LATTE_140', hex: '#d1c4b2', type: 'ic' },
    { name: 'PARADISE_20', hex: '#cffafe', type: 'ic' }, { name: 'CARMEN_130', hex: '#7f1d1d', type: 'ic' },
    { name: 'DAISY_95', hex: '#facc15', type: 'ic' }, { name: 'LATTE_185', hex: '#beaf9d', type: 'ic' },
    { name: 'MARZIPAN_65', hex: '#fde047', type: 'ic' }, { name: 'LATTE_115', hex: '#d1c2ae', type: 'ic' },
    { name: 'NECTAR_55', hex: '#fde68a', type: 'ic' }, { name: 'BONSAI_105', hex: '#a3e635', type: 'ic' },
    { name: 'DAISY_165', hex: '#854d0e', type: 'ic' }, { name: 'CARNAVAL_10', hex: '#fdf2f8', type: 'ic' },
    { name: 'LATTE_180', hex: '#c3b3a1', type: 'ic' }, { name: 'LATTE_125', hex: '#cbc0ae', type: 'ic' },
    { name: 'MARZIPAN_115', hex: '#ca8a04', type: 'ic' }, { name: 'MARZIPAN_35', hex: '#fef9c3', type: 'ic' },
    { name: 'SALSA_15', hex: '#fecaca', type: 'ic' }, { name: 'NECTAR_45', hex: '#fef08a', type: 'ic' },
    { name: 'FOREST_40', hex: '#dcfce7', type: 'ic' }, { name: 'LATTE_40', hex: '#f0e9dd', type: 'ic' },
    { name: 'CANVAS_60', hex: '#f1ebe0', type: 'ic' }, { name: 'FOREST_20', hex: '#f0fdf4', type: 'ic' },
    { name: 'CREAM_10', hex: '#fffbeb', type: 'ic' }, { name: 'CARMEN_75', hex: '#dc2626', type: 'ic' },
    { name: 'NECTAR_165', hex: '#a16207', type: 'ic' }, { name: 'APRIL_15', hex: '#f0fdf4', type: 'ic' },
    { name: 'LILAC_95', hex: '#f5f3ff', type: 'ic' }, { name: 'LILAC_145', hex: '#ddd6fe', type: 'ic' },
    { name: 'NECTAR_10', hex: '#fffbeb', type: 'ic' }, { name: 'CANVAS_70', hex: '#efe7db', type: 'ic' },
    { name: 'MARZIPAN_60', hex: '#fde047', type: 'ic' }, { name: 'BONSAI_70', hex: '#d9f99d', type: 'ic' },
    { name: 'MARZIPAN_70', hex: '#fde047', type: 'ic' }, { name: 'DAISY_10', hex: '#fffdf0', type: 'ic' },
    { name: 'MIST_75', hex: '#e2e8f0', type: 'ic' }, { name: 'DAISY_155', hex: '#a16207', type: 'ic' },
    { name: 'FOREST_215', hex: '#064e3b', type: 'ic' }, { name: 'DAISY_65', hex: '#fde047', type: 'ic' },
    { name: 'AQUA_5', hex: '#f0f9ff', type: 'ic' }, { name: 'BONSAI_140', hex: '#65a30d', type: 'ic' },
    { name: 'BAL SARISI', hex: '#fbbf24', type: 'ic' }, { name: 'İNCİ ÇİÇEĞİ', hex: '#fff7ed', type: 'ic' },
    { name: 'CANVAS_170', hex: '#d1c7ba', type: 'ic' }, { name: 'BONSAI_190', hex: '#365314', type: 'ic' },
    { name: 'LATTE_210', hex: '#d1c0ad', type: 'ic' }, { name: 'BONSAI_5', hex: '#f7fee7', type: 'ic' },
    { name: 'CANVAS_120', hex: '#e2d9cb', type: 'ic' }, { name: 'COTTON_5', hex: '#f9fafb', type: 'ic' },
    { name: 'FOREST_165', hex: '#14532d', type: 'ic' }, { name: 'CANVAS_105', hex: '#e5dbca', type: 'ic' },
    { name: 'DAISY_175', hex: '#713f12', type: 'ic' }, { name: 'LILAC_170', hex: '#c084fc', type: 'ic' },
    { name: 'MIST_30', hex: '#f8fafc', type: 'ic' }, { name: 'CARMEN_45', hex: '#f87171', type: 'ic' },
    { name: 'CANVAS_160', hex: '#d9cfbe', type: 'ic' }, { name: 'FOREST_155', hex: '#166534', type: 'ic' },
    { name: 'FOREST_200', hex: '#064e3b', type: 'ic' }, { name: 'NECTAR_95', hex: '#f59e0b', type: 'ic' },
    { name: 'LILAC_10', hex: '#faf5ff', type: 'ic' }, { name: 'MARZIPAN_30', hex: '#fef9c3', type: 'ic' },
    { name: 'DENIM_10', hex: '#f0f9ff', type: 'ic' }, { name: 'LILAC_75', hex: '#f3e8ff', type: 'ic' },
    { name: 'NECTAR_70', hex: '#fbbf24', type: 'ic' }, { name: 'DAISY_20', hex: '#fffbeb', type: 'ic' },
    { name: 'CARMEN_95', hex: '#991b1b', type: 'ic' }, { name: 'BONSAI_65', hex: '#d9f99d', type: 'ic' },
    { name: 'SATIN_20', hex: '#e2e8f0', type: 'ic' }, { name: 'NECTAR_100', hex: '#f59e0b', type: 'ic' },
    { name: 'DAISY_5', hex: '#fffdf0', type: 'ic' }, { name: 'FOREST_55', hex: '#4ade80', type: 'ic' },
    { name: 'FOREST_90', hex: '#22c55e', type: 'ic' }, { name: 'CARMEN_40', hex: '#ef4444', type: 'ic' },
    { name: 'FOREST_60', hex: '#4ade80', type: 'ic' }, { name: 'DAISY_90', hex: '#facc15', type: 'ic' },
    { name: 'NECTAR_85', hex: '#fbbf24', type: 'ic' }, { name: 'CANVAS_45', hex: '#f5f2eb', type: 'ic' },
    { name: 'LILAC_85', hex: '#f3e8ff', type: 'ic' }, { name: 'COTTON_10', hex: '#f9fafb', type: 'ic' },
    { name: 'LILAC_20', hex: '#faf5ff', type: 'ic' }, { name: 'NECTAR_145', hex: '#b45309', type: 'ic' },
    { name: 'FOREST_15', hex: '#f0fdf4', type: 'ic' }, { name: 'AÇIK MAVİ', hex: '#bae6fd', type: 'ic' },
    { name: 'MARZIPAN_120', hex: '#ca8a04', type: 'ic' }, { name: 'BONSAI_175', hex: '#3f6212', type: 'ic' },
    { name: 'DAISY_15', hex: '#fffbeb', type: 'ic' }, { name: 'BONSAI_230', hex: '#365314', type: 'ic' },
    { name: 'MARZIPAN_90', hex: '#facc15', type: 'ic' }, { name: 'PARADISE_10', hex: '#ecfeff', type: 'ic' },
    { name: 'MIST_50', hex: '#f1f5f9', type: 'ic' }, { name: 'FOREST_35', hex: '#dcfce7', type: 'ic' },
    { name: 'CARMEN_140', hex: '#450a0a', type: 'ic' }, { name: 'DENIM_60', hex: '#bfdbfe', type: 'ic' },
    { name: 'FOREST_70', hex: '#4ade80', type: 'ic' }, { name: 'KANVAS', hex: '#f5f5dc', type: 'ic' },
    { name: 'WIND_10', hex: '#f8fafc', type: 'ic' }, { name: 'LILAC_15', hex: '#faf5ff', type: 'ic' },
    { name: 'SPA_10', hex: '#ecfeff', type: 'ic' }, { name: 'DENIM_150', hex: '#2563eb', type: 'ic' },
    { name: 'FOREST_85', hex: '#22c55e', type: 'ic' }, { name: 'MARZIPAN_150', hex: '#713f12', type: 'ic' },
    { name: 'FLORA_15', hex: '#f0fdf4', type: 'ic' }, { name: 'DAISY_145', hex: '#a16207', type: 'ic' },
    { name: 'ŞAMPANYA', hex: '#fdf5e6', type: 'ic' }, { name: 'CARMEN_60', hex: '#dc2626', type: 'ic' },
    { name: 'LEYLAK', hex: '#c084fc', type: 'ic' }, { name: 'BONSAI_80', hex: '#d9f99d', type: 'ic' },
    { name: 'DAISY_135', hex: '#ca8a04', type: 'ic' }, { name: 'MIST_65', hex: '#e2e8f0', type: 'ic' },
    { name: 'FOREST_220', hex: '#064e3b', type: 'ic' }, { name: 'CARNAVAL_20', hex: '#fbcfe8', type: 'ic' },
    { name: 'POWDER_10', hex: '#fdf2f8', type: 'ic' }, { name: 'LILAC_65', hex: '#f3e8ff', type: 'ic' },
    { name: 'NECTAR_90', hex: '#fbbf24', type: 'ic' }, { name: 'DAISY_115', hex: '#eab308', type: 'ic' },
    { name: 'NECTAR_5', hex: '#fffbeb', type: 'ic' }, { name: 'FOREST_225', hex: '#022c22', type: 'ic' },
    { name: 'BONSAI_210', hex: '#3f6212', type: 'ic' }, { name: 'CANVAS_40', hex: '#f5f2ec', type: 'ic' },
    { name: 'BONSAI_110', hex: '#a3e635', type: 'ic' }, { name: 'İĞDE', hex: '#65a30d', type: 'ic' },
    { name: 'POWDER_15', hex: '#fce7f3', type: 'ic' }, { name: 'CARMEN_135', hex: '#450a0a', type: 'ic' },
    { name: 'MIST_105', hex: '#d1d5db', type: 'ic' }, { name: 'CARMEN_110', hex: '#991b1b', type: 'ic' },
    { name: 'MIST_115', hex: '#d1d5db', type: 'ic' }, { name: 'FLORA_20', hex: '#dcfce7', type: 'ic' },
    { name: 'MIST_35', hex: '#f8fafc', type: 'ic' }, { name: 'CARMEN_145', hex: '#450a0a', type: 'ic' },
    { name: 'DAISY_30', hex: '#fefce8', type: 'ic' }, { name: 'MIST_60', hex: '#e2e8f0', type: 'ic' },
    { name: 'İSTİRİDYE', hex: '#e5e7eb', type: 'ic' }, { name: 'LILAC_200', hex: '#a855f7', type: 'ic' },
    { name: 'LILAC_110', hex: '#ddd6fe', type: 'ic' }, { name: 'AQUA_20', hex: '#bae6fd', type: 'ic' },
    { name: 'BONSAI_195', hex: '#365314', type: 'ic' }, { name: 'NECTAR_175', hex: '#92400e', type: 'ic' },
    { name: 'NİL YEŞİLİ', hex: '#2dd4bf', type: 'ic' }, { name: 'CLAY_20', hex: '#e7e5e4', type: 'ic' },
    { name: 'MARZIPAN_40', hex: '#fef9c3', type: 'ic' }, { name: 'NECTAR_50', hex: '#fde68a', type: 'ic' },
    { name: 'BONSAI_120', hex: '#84cc16', type: 'ic' }, { name: 'CREAM_20', hex: '#fef3c7', type: 'ic' },
    { name: 'CARMEN_100', hex: '#991b1b', type: 'ic' }, { name: 'FOREST_195', hex: '#064e3b', type: 'ic' },
    { name: 'DAISY_45', hex: '#fef9c3', type: 'ic' }, { name: 'NECTAR_125', hex: '#b45309', type: 'ic' },
    { name: 'LILAC_185', hex: '#c084fc', type: 'ic' }, { name: 'LATTE_85', hex: '#dad0c0', type: 'ic' },
    { name: 'LILAC_30', hex: '#f5f3ff', type: 'ic' }, { name: 'MIST_80', hex: '#e2e8f0', type: 'ic' },
    { name: 'DENIM_135', hex: '#2563eb', type: 'ic' }, { name: 'DENIM_20', hex: '#f0f9ff', type: 'ic' },
    { name: 'CANVAS_180', hex: '#c9bfb0', type: 'ic' }, { name: 'FOREST_185', hex: '#064e3b', type: 'ic' },
    { name: 'ROMANTIC_5', hex: '#fff1f2', type: 'ic' }, { name: 'MARZIPAN_105', hex: '#eab308', type: 'ic' },
    { name: 'FOREST_205', hex: '#064e3b', type: 'ic' }, { name: 'CARMEN_105', hex: '#991b1b', type: 'ic' },
    { name: 'DAISY_100', hex: '#facc15', type: 'ic' }, { name: 'CARMEN_65', hex: '#dc2626', type: 'ic' },
    { name: 'CARNAVAL_5', hex: '#fff1f2', type: 'ic' }, { name: 'NECTAR_115', hex: '#b45309', type: 'ic' },
    { name: 'CREAM_15', hex: '#fef3c7', type: 'ic' }, { name: 'LATTE_60', hex: '#e6dbcc', type: 'ic' },
    { name: 'NECTAR_40', hex: '#fef08a', type: 'ic' }, { name: 'NECTAR_135', hex: '#92400e', type: 'ic' },
    { name: 'BONSAI_225', hex: '#365314', type: 'ic' }, { name: 'DAISY_120', hex: '#eab308', type: 'ic' },
    { name: 'MARZIPAN_95', hex: '#facc15', type: 'ic' }, { name: 'MIST_85', hex: '#e2e8f0', type: 'ic' },
    { name: 'CANVAS_95', hex: '#e8decb', type: 'ic' }, { name: 'NECTAR_170', hex: '#92400e', type: 'ic' },
    { name: 'FOREST_25', hex: '#f0fdf4', type: 'ic' }, { name: 'CARMEN_50', hex: '#ef4444', type: 'ic' },
    { name: 'LATTE_80', hex: '#dfd4c4', type: 'ic' }, { name: 'LILAC_60', hex: '#f3e8ff', type: 'ic' },
    { name: 'RÜZGAR', hex: '#f1f5f9', type: 'ic' }, { name: 'SPA_20', hex: '#bae6fd', type: 'ic' },
    { name: 'LILAC_150', hex: '#ddd6fe', type: 'ic' }, { name: 'FİL DİŞİ', hex: '#fffff0', type: 'ic' },
    { name: 'BONSAI_50', hex: '#f7fee7', type: 'ic' }, { name: 'LATTE_25', hex: '#f7f2ea', type: 'ic' },
    { name: 'CANVAS_10', hex: '#fafaf9', type: 'ic' }, { name: 'BAHAR LİLASI', hex: '#e9d5ff', type: 'ic' },
    { name: 'BONSAI_60', hex: '#d9f99d', type: 'ic' }, { name: 'DENIM_115', hex: '#3b82f6', type: 'ic' },
    { name: 'EKRU', hex: '#fefdf0', type: 'ic' }, { name: 'LILAC_100', hex: '#f5f3ff', type: 'ic' },
    { name: 'FOREST_5', hex: '#f0fdf4', type: 'ic' }, { name: 'NECTAR_155', hex: '#a16207', type: 'ic' },
    { name: 'MARZIPAN_145', hex: '#854d0e', type: 'ic' }, { name: 'LILAC_50', hex: '#f3e8ff', type: 'ic' },
    { name: 'WIND_5', hex: '#f8fafc', type: 'ic' }, { name: 'MIST_20', hex: '#f8fafc', type: 'ic' },
    { name: 'DENIM_130', hex: '#2563eb', type: 'ic' }, { name: 'LILAC_115', hex: '#ddd6fe', type: 'ic' },
    { name: 'LATTE_170', hex: '#c0b1a0', type: 'ic' }, { name: 'MIST_55', hex: '#f1f5f9', type: 'ic' },
    { name: 'NECTAR_35', hex: '#fef3c7', type: 'ic' }, { name: 'FOREST_210', hex: '#064e3b', type: 'ic' },
    { name: 'ROMANTIC_15', hex: '#fce7f3', type: 'ic' }, { name: 'NECTAR_75', hex: '#fbbf24', type: 'ic' },
    { name: 'LATTE_5', hex: '#fdfbf9', type: 'ic' }, { name: 'LILAC_180', hex: '#c084fc', type: 'ic' },
    { name: 'MIST_5', hex: '#fafafa', type: 'ic' }, { name: 'NECTAR_180', hex: '#92400e', type: 'ic' },
    { name: 'BONSAI_155', hex: '#65a30d', type: 'ic' }, { name: 'LILAC_55', hex: '#f3e8ff', type: 'ic' },
    { name: 'LATTE_165', hex: '#c4b5a3', type: 'ic' }, { name: 'BONSAI_165', hex: '#3f6212', type: 'ic' },
    { name: 'MARZIPAN_130', hex: '#ca8a04', type: 'ic' }, { name: 'MARZIPAN_15', hex: '#fef3c7', type: 'ic' },
    { name: 'APRIL_10', hex: '#f0fdf4', type: 'ic' }, { name: 'LATTE_160', hex: '#c7b8a7', type: 'ic' },
    { name: 'CANVAS_25', hex: '#faf7f2', type: 'ic' }, { name: 'LATTE_150', hex: '#cebfac', type: 'ic' },
    { name: 'MIST_100', hex: '#e2e8f0', type: 'ic' }, { name: 'IVORY_15', hex: '#fffff0', type: 'ic' },
    { name: 'DAISY_160', hex: '#854d0e', type: 'ic' }, { name: 'BANANA_10', hex: '#fffdf0', type: 'ic' },
    { name: 'DENIM_30', hex: '#f0f9ff', type: 'ic' }, { name: 'DENIM_145', hex: '#2563eb', type: 'ic' },
    { name: 'DENIM_160', hex: '#1d4ed8', type: 'ic' }, { name: 'FOREST_65', hex: '#4ade80', type: 'ic' },
    { name: 'FISTIK', hex: '#a3e635', type: 'ic' }, { name: 'CANVAS_145', hex: '#ddd2c2', type: 'ic' },
    { name: 'DENIM_90', hex: '#60a5fa', type: 'ic' }, { name: 'CARMEN_85', hex: '#b91c1c', type: 'ic' },
    { name: 'LATTE_130', hex: '#d1c4b1', type: 'ic' }, { name: 'CANVAS_190', hex: '#c2b6a5', type: 'ic' },
    { name: 'CLAY_15', hex: '#f5f5f4', type: 'ic' }, { name: 'IVORY_20', hex: '#fffff0', type: 'ic' },
    { name: 'BONSAI_90', hex: '#bef264', type: 'ic' }, { name: 'FOREST_135', hex: '#166534', type: 'ic' },
    { name: 'CANVAS_30', hex: '#f7f4ee', type: 'ic' }, { name: 'DAISY_105', hex: '#facc15', type: 'ic' },
    { name: 'BONSAI_135', hex: '#4d7c0f', type: 'ic' }, { name: 'LILAC_175', hex: '#c084fc', type: 'ic' },
    { name: 'ZEN_20', hex: '#f3f4f6', type: 'ic' }, { name: 'MARZIPAN_25', hex: '#fefce8', type: 'ic' },
    { name: 'LATTE_10', hex: '#faf8f5', type: 'ic' }, { name: 'FOREST_190', hex: '#064e3b', type: 'ic' },
    { name: 'SATIN_15', hex: '#f1f5f9', type: 'ic' }, { name: 'BONSAI_205', hex: '#3f6212', type: 'ic' },
    { name: 'FOREST_125', hex: '#166534', type: 'ic' }, { name: 'IVORY_10', hex: '#fffff0', type: 'ic' },
    { name: 'KETEN BEJİ', hex: '#d2b48c', type: 'ic' }, { name: 'LILAC_165', hex: '#c084fc', type: 'ic' },
    { name: 'NECTAR_65', hex: '#fbbf24', type: 'ic' }, { name: 'BONSAI_45', hex: '#f7fee7', type: 'ic' },
    { name: 'CANVAS_110', hex: '#e8dfcd', type: 'ic' }, { name: 'NECTAR_80', hex: '#fbbf24', type: 'ic' },
    { name: 'SU DAMLASI', hex: '#e0f2fe', type: 'ic' }, { name: 'NECTAR_190', hex: '#78350f', type: 'ic' },
    { name: 'BONSAI_220', hex: '#365314', type: 'ic' }, { name: 'LATTE_135', hex: '#d4c5b3', type: 'ic' },
    { name: 'MIST_70', hex: '#e2e8f0', type: 'ic' }, { name: 'POLEN', hex: '#fde047', type: 'ic' },
    { name: 'CARMEN_90', hex: '#b91c1c', type: 'ic' }, { name: 'BONSAI_160', hex: '#3f6212', type: 'ic' },
    { name: 'DENIM_80', hex: '#93c5fd', type: 'ic' }, { name: 'BONSAI_35', hex: '#ecfccb', type: 'ic' },
    { name: 'IVORY_5', hex: '#fffcf2', type: 'ic' }, { name: 'NECTAR_140', hex: '#b45309', type: 'ic' },
    { name: 'DENIM_25', hex: '#f0f9ff', type: 'ic' }, { name: 'DAISY_110', hex: '#facc15', type: 'ic' },
    { name: 'CANVAS_195', hex: '#c0b4a2', type: 'ic' }, { name: 'FOREST_105', hex: '#22c55e', type: 'ic' },
    { name: 'NECTAR_60', hex: '#fde68a', type: 'ic' }, { name: 'CANVAS_150', hex: '#dbcfbf', type: 'ic' },
    { name: 'BONSAI_150', hex: '#65a30d', type: 'ic' }, { name: 'COTTON_15', hex: '#f9fafb', type: 'ic' },
    { name: 'ZEN_15', hex: '#f9fafb', type: 'ic' }, { name: 'DENIM_140', hex: '#2563eb', type: 'ic' },
    { name: 'LILAC_160', hex: '#c084fc', type: 'ic' }, { name: 'DAISY_55', hex: '#fde047', type: 'ic' },
    { name: 'DAISY_130', hex: '#ca8a04', type: 'ic' }, { name: 'ROMANTIC_10', hex: '#fdf2f8', type: 'ic' },
    { name: 'PUDRA MAVİ', hex: '#bfdbfe', type: 'ic' }, { name: 'LILAC_80', hex: '#f3e8ff', type: 'ic' },
    { name: 'DAISY_50', hex: '#fef08a', type: 'ic' }, { name: 'BONSAI_55', hex: '#d9f99d', type: 'ic' },
    { name: 'DAISY_70', hex: '#fde047', type: 'ic' }, { name: 'DENIM_15', hex: '#f0f9ff', type: 'ic' },
    { name: 'JASMINE_10', hex: '#fff7ed', type: 'ic' }, { name: 'NECTAR_200', hex: '#78350f', type: 'ic' },
    { name: 'LILAC_120', hex: '#ddd6fe', type: 'ic' }, { name: 'MARZIPAN_75', hex: '#fde047', type: 'ic' },
    { name: 'CARMEN_150', hex: '#450a0a', type: 'ic' }, { name: 'MIST_110', hex: '#d1d5db', type: 'ic' },
    { name: 'DAISY_170', hex: '#854d0e', type: 'ic' }, { name: 'GÜLPEMBE', hex: '#fda4af', type: 'ic' },
    { name: 'BONSAI_85', hex: '#bef264', type: 'ic' }, { name: 'BONSAI_250', hex: '#1a2e05', type: 'ic' },
    { name: 'FOREST_50', hex: '#4ade80', type: 'ic' }
    ];
